added an .env.example file
supabase-community/supabase-community-bot pull request #3
Opened 2022-12-18 06:27 UTC by reddiedev

added an env template for relatively faster and easier project setup for collaborators

2022-12-18 06:28 UTC, reddiedev commented
I just added this one here separately, as you have suggested. I'll add the events folder/files revamp in the next PR!

2022-12-18 09:18 UTC, reddiedev commented
## one file for each event
makes it easier to modify and add more events in the future, since you only need to worry about one event at a time. events will be loosely coupled and will be more locally scoped 

## event handler in index.ts
added the event handler in the index file for easier reading

2022-12-20 11:04 UTC, Olyno requested changes
Hey 👋🏻 Thanks for your patience and for making another pull request! I made a first review for you. Don't hesitate to send me your feedback if you don't agree on some points, or if you have difficulties with some parts  😃

2023-01-26 07:52 UTC, MagnusHJensen commented on src/index.ts
> +}
Wouldn't something like file-based discovery of events and commands be better, and less stuff to maintain?

2023-01-26 12:39 UTC, Olyno commented on src/index.ts
> +}
Do you have an example of what you have in mind? Like the structure?

2023-01-30 18:49 UTC, closed without merging